using System;
using System.Collections.Generic;

namespace ProjectEuler
{
    // How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
    public static class P029
    {
        public static int Solve()
        {
            // i use double and allow overflows because 
            // i'm only interested in Count, not exact values
            var c = new HashSet<double>();

            for (int a = 2; a <= 100; a++)
            {
                for (int b = 2; b <= 100; b++)
                {
                    c.Add(Math.Pow(a, b));
                }
            }

            return c.Count;
        }
    }
}
